version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: academic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-academic_datamart}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-academic123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-datamarts.sql:/docker-entrypoint-initdb.d/init-datamarts.sql
    networks:
      - academic_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-academic_datamart}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: academic_qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY:-qdrant123}
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - academic_network

  # Data Generator & Trainer
  data-trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: academic_trainer
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - POSTGRES_DB=${POSTGRES_DB:-academic_datamart}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-academic123}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:-qdrant123}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./logs:/app/logs
      - ./trainers:/app/trainers
    networks:
      - academic_network
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    command: ["python", "train_main.py"]

volumes:
  postgres_data:
  qdrant_data:

networks:
  academic_network:
    driver: bridge